language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0

env:
  - WP_VERSION=5.8.1 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - phpunit --version

script: phpunit
